export const START_GETTING_TABLE_DATA='START_GETTING_TABLE_DATA';
export const GET_TABLE_DATA='GET_TABLE_DATA';
export const STOP_GETTING_TABLE_DATA='STOP_GETTING_TABLE_DATA';


export const START_GETTING_LINE_CHART_DATA='START_GETTING_LINE_CHART_DATA';
export const GET_LINE_CHART_DATA='GET_LINE_CHART_DATA';
export const STOP_GETTING_LINE_CHART_DATA='STOP_GETTING_LINE_CHART_DATA';